language: python
python:
- '2.7'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
before_install:
- export DJANGO_SETTINGS_MODULE=mysite.settings
install:
- pip install -r requirements.txt
- pip install coveralls
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py test service.tests
- coverage run --source=service manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: mpNvO7V11HI4a2UOCrav9YfK0sn68owkIghR9+UDdAagsUmGvwJ1TIueITKNJxwwPXSwmaaHbbTZaaST/2TuZV/b8zSs6ffGOYoMiUlObYhfrMUcsdsqMlOSMOph77x20w1LJ+HnUqvj4dxRHIr/eXWlh3uPlzVeoPnj/63YKwoUKIWVHaLMltNHu5aK0XG9/qx+3EAwtTV5g5lYhbQRdmPi8rHu5Ye9xAwwewGPjVm/FK1uPm2Zf//0jRlcCwezvgCT/3r4Unq+pE4tXtJknxB4zJZlKAQAzp78NrWwfE0vks6QuoaSPQJsGNde+GnGE4ZcpFfDAvFmyaq82rloZcEsIvJ3ITzeUe320PWGE6IVu5zuP2PT732PpkmQ1/wVK2YvPICSf5BOWRduGrJEycDrli/y4jPLBzP2xU9ya99se9F+nRcM/nerma3E6QBWkCeQ2tqyYfATTEg70NHyl3Iz0IKlT0ds1CW59lEMelpnnhn44v1CV1Bca5o0sTje8o/7Vgt7y8zHBxFtk5T8YZe/1U9hAh/lCx5GhrtQpRhPvz8Es2obSyP99STh9xbDfpEDt6kmU2ON+GsdNR2fL1t1TLahyWo4qd/NRZNnpaMMwubHLUtCCZGmu3dz452FTkZMabi/EQ9lsWYK0RLFnvOXq+/Yri//IYo+tm5qjVY=
  app: bookturks
  on:
    repo: zalokhan/BookTurks
env:
  secure: P2SkGl/7euUeLFjrBo3DDQTqQWaMrRvOfuD37ro+8yMcuTdtZZEUk+pXWtLXpwdWzak5CPrz8SzVKHr9+mzATTvY0bTdnGLboPIgPTTOeef8UBpU0omRXQKa31pnlWzNw7fwY8UKrfle6Yc+Ms5jCpuaMwangnnMB+ky5beIGpUUL/N6kAVBgQQ6P0WzRl1pBy4fbwzXU+f3GyXQw24GVw8PpaXqSjDEazJ/hjSylL6AuBi185tXxhQLc7/zZmC8GtSwlkFnKMf0S0NwHhdrecX/yfVO6nLJqKTta/RFHmvI5DCDcDW6ZaHySKK0kOQh92hfsCkWxpke+/n41+ldr68b6FCfDvA8pIpm0Ke9hEl3bm36uCC6gKSAx9Dfsv7RtGrCrjMhcAkmFB8RnSzJWRlNQUjzRvI9wwM95MvCjm4z+hfoLz7sLA/q8wKSktL7kEs4w1wueQsoTSVmJM9X7RYNBIBcJwC8EUzI/ex0xcQ1uAXwV2XCT1nbpz9bKNmUed3AXHcdqM+b9qSfmVM2YYb2t2FRdIMfPK9m3ucoIA/UiF5dDpJ64Z3dMR5adRcWHfKMA6NM4pv+Css0AtiTsn8PQ4w1JsmZ1zYL0tF661leR7rjpxqBWrnHeALFftyFIzy6hdZxzwpjaFssbSzsebBJvsMW1059fWOMnOfGOIk=
  global:
    secure: Ug6Yor3YVUUGGJAN7Hn/MI8RWrKFPsoFz53tuci8P5WsHpD2sxqEMWvtLjcj9Hmlww8JfcBnH9R4z57GhDeCh1tcBunj/eajDBYjDbbfmI9TRvkZt5FgdGVNvi2inbF1uaDYi2I7aaebNQW1CNyoErtHEOrmBNme9Dep0OzMlUM1ttyjiTJOrZCdSgvRNDsc6m5tcNOsMadEwOvTAcBo3YJhNU7tjwX1qPBT4ysFZYoRUNMiaSNycrQxBZjBJn/4mCj1hh84Su2ue+3PXlpvYnZIhd3+sWql2JY4YBU+hV6RrBJgr5xf5N/02VPwlFWBcKEC0+PM0FV3BETMEByYL05atqmp6RQNSs4/VC/do0LXRUtEKi0BgYZsKdQCKd9Yc2Jho7UTv+uJsv7CLUW5k18XPM3g9C5om5oRPVNz8G1tUwD5VBVXm+RgZ754hRmn2e09bqHxYTRpnVHYhi/praIQD1XdistYU7ly5AjXMWpBWEf7lK6LcX4f+rXCfCw2GQYyZF+WR7NnUYmXJjrjxetIdQCUnSWWwG/YyuPcFuEqg9BIfhK+JwRTy/OVEl7X7U9vsmJhdYxy1DIU9+UgSGODRrmyhwEedFDn39JlzTfH/mfAFU3BNcdgCg0EiCiMP/gCZZNWJCUCqEis0w1QW3u+viY+oh49piNAFBHlDrM=
