language: python
python:
- '2.7'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
before_install:
- export DJANGO_SETTINGS_MODULE=mysite.settings
install:
- pip install -r requirements.txt
- pip install coveralls
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py test service.tests
- coverage run --source=service manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: h+B6fvBPx2YhH+bKwYWwp3IAqgdDiXdysLuHsjHMrBwIvDxfSPY7yCi0JywMbXBzUTf9X0zOY8M5IXsQ3C+46E3vYDHviwck+QnMrxNX+pLWbEgun3r3oyjvLygoUB23L8doWoIFIttfHyywmSB5E33j0GRxmIeUB3XqFFc515P4ZD+djjbuoNx8jSsLPrcyf5mzowSd6wWVbXHIaD349d6AYQmo7VmZKK0YxUqCgnnDHb9CR+gk4QxGFsZnbQR0wX4gzDtkEXT+Ng2crKyzjwassC6WAD3u8NMys7Rg42/lzk5D4mnUThsXDRDEdLPJ3idB4pKieVeH/U/yPBdJ8dZbx6fQ8/DMWTKPM+nT7dqH+jQmStLxfDM0XrPikDZswaQhyuofqul6xI5b2ronkdMzPaoBXN/tyUEXnfHUUjEfWu/o+CpoGOQoLmmv3/5/ElqufwoAjvp5zivMaVyTrxFG3MY1XHfETOr2M/91WDF3gahoOq3AJX9WKrbBAc6PoTy8q9Rc3ap38QtfD8pAvxAr5/Jp0SHfcVZ05o5HK/17xk4gbZa5wHZDiJSxcCG/NPzpNzSubw1pfnGOP7SUHr2JLf1Ln14mfWRut3cf2rsYRgPbhw1fWgEHSXjwc7z/6LUwbKlxtRMRZfZU2pMesr0Eeys6D1qKKWkSK/3TAug=
  app: zee-service-dev
  on:
    repo: zalokhan/BookTurks
env:
  secure: P2SkGl/7euUeLFjrBo3DDQTqQWaMrRvOfuD37ro+8yMcuTdtZZEUk+pXWtLXpwdWzak5CPrz8SzVKHr9+mzATTvY0bTdnGLboPIgPTTOeef8UBpU0omRXQKa31pnlWzNw7fwY8UKrfle6Yc+Ms5jCpuaMwangnnMB+ky5beIGpUUL/N6kAVBgQQ6P0WzRl1pBy4fbwzXU+f3GyXQw24GVw8PpaXqSjDEazJ/hjSylL6AuBi185tXxhQLc7/zZmC8GtSwlkFnKMf0S0NwHhdrecX/yfVO6nLJqKTta/RFHmvI5DCDcDW6ZaHySKK0kOQh92hfsCkWxpke+/n41+ldr68b6FCfDvA8pIpm0Ke9hEl3bm36uCC6gKSAx9Dfsv7RtGrCrjMhcAkmFB8RnSzJWRlNQUjzRvI9wwM95MvCjm4z+hfoLz7sLA/q8wKSktL7kEs4w1wueQsoTSVmJM9X7RYNBIBcJwC8EUzI/ex0xcQ1uAXwV2XCT1nbpz9bKNmUed3AXHcdqM+b9qSfmVM2YYb2t2FRdIMfPK9m3ucoIA/UiF5dDpJ64Z3dMR5adRcWHfKMA6NM4pv+Css0AtiTsn8PQ4w1JsmZ1zYL0tF661leR7rjpxqBWrnHeALFftyFIzy6hdZxzwpjaFssbSzsebBJvsMW1059fWOMnOfGOIk=
