language: python
python:
- '2.7'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
before_install:
- export DJANGO_SETTINGS_MODULE=mysite.settings
install:
- pip install -r requirements.txt
- pip install coveralls
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py test service.tests
- coverage run --source=service manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: mpNvO7V11HI4a2UOCrav9YfK0sn68owkIghR9+UDdAagsUmGvwJ1TIueITKNJxwwPXSwmaaHbbTZaaST/2TuZV/b8zSs6ffGOYoMiUlObYhfrMUcsdsqMlOSMOph77x20w1LJ+HnUqvj4dxRHIr/eXWlh3uPlzVeoPnj/63YKwoUKIWVHaLMltNHu5aK0XG9/qx+3EAwtTV5g5lYhbQRdmPi8rHu5Ye9xAwwewGPjVm/FK1uPm2Zf//0jRlcCwezvgCT/3r4Unq+pE4tXtJknxB4zJZlKAQAzp78NrWwfE0vks6QuoaSPQJsGNde+GnGE4ZcpFfDAvFmyaq82rloZcEsIvJ3ITzeUe320PWGE6IVu5zuP2PT732PpkmQ1/wVK2YvPICSf5BOWRduGrJEycDrli/y4jPLBzP2xU9ya99se9F+nRcM/nerma3E6QBWkCeQ2tqyYfATTEg70NHyl3Iz0IKlT0ds1CW59lEMelpnnhn44v1CV1Bca5o0sTje8o/7Vgt7y8zHBxFtk5T8YZe/1U9hAh/lCx5GhrtQpRhPvz8Es2obSyP99STh9xbDfpEDt6kmU2ON+GsdNR2fL1t1TLahyWo4qd/NRZNnpaMMwubHLUtCCZGmu3dz452FTkZMabi/EQ9lsWYK0RLFnvOXq+/Yri//IYo+tm5qjVY=
  app: bookturks
  on:
    repo: zalokhan/BookTurks
env:
  global:
  # DJANGO
  - secure: TY54FcUcTj0cZ0e6IEmdMzFuEOIjGqdyC7YFSP/MNYwcOjzex9KofIy8hUquBowYl64SNCs7CHSh8XSGRFNDobdfDjThFEJNKNIryzZ0Z8VMacBGgqmPdJ/rtxKYyyKi1gLYmqtPD9KVxB364e+SPIe7QrgppNyRpO0x/aa2RXieVdHl9eX35CLuWd8wAKWT/pAyKdTTQOQ9C5TTzH5Agw3ruiQh++8TNt6dTuUx5oCU/rUKRq6PGp90b/7ZhkLdBx9BaQvQX1MrA5dFg2oKfFWaWf6RzSH2LHhWk9h3lQvwi2NtLyk4xW3jFB62ULj5Ns7mQybRf27J4nw33lyQjJo2w05AQcS3G437VF1ueTrA7z/dBFCifI0Lli0PBCpiDWPRhrzhGm7GL1jesBQc2V/hCwZG8sQeoKc3oJeHkkEYl9u5MUHzjsbsWNYxWc4veWP7mL+9GkhVUWZvXgrEVCr3iEfjzl+i1QFvYdYB/Dq51P08Lf3UB6bi5YoZf3YsEDYqtGdde33+r5PLywIQOIfH9G/vXtFbcPITYyvvmHFaDCkbzAXb6A+XxFXvLQs8+mBvVRquGT1mM2gfMlkatx3+0yr3ramEkIyZ9vtVeN0uA7NqL4ORsV9S1Apfw8zvBqdM4aourMimBffXZ9oY5RMRzh+SwN0QSb0ofpbGTRs=
  # SOCIAL
  # FB
  - secure: ELGYPVGbvYne1F6dRQcKh8FEyeusaCj3t9eYPqVKubIwvyhxLzjqITulapxNGE+4aKf0mCi/zVuQOeOLjUr3uebde5DFIdjHjrHoYqUaRH1KbjTmJU7J5st4ejKAUheUQ8Y+s1SBI2WFX/+HOJeqN9dK1WhqkHycApoTFx9LL9gmVq/833RJmslOMtosDxkYbRnRPk5k5NSYzvIOmwALKJXo8GCkQBz5Koda4+yB2u7d42MYI1Y8sbr1nAVPlhDxqIWvfplitI3+adofVThYU+F8j/ijRGJaQRjQJ7qqyywMkXBS67/+ctZV4XD82CGRglAWTY0EYIsCjPwKkrb8GwQCmo5YzOR1sfQfb4sqaw7ofQlumktwoI52ME2/KSC7I+cc+4x6imW6MTfseJAK4qVnZULQDLv7wMvx/znNH7IuwC/de5YQXltcwXz8euXYnvTDS85V2mfEDHGq0YqWL7xLpABY9ku4b5M6Dc4o7aVszBBjcjny2V4z7i6WuF5yDrul3sfEnb6bgbqLD5EEdqe2EP95JGRrWbMswz52LEsepIt9b2pSB2Hf5AZK9jB3rD9fhGfPHKO594beaDJUSnwTfrnxUaREAuDA4cYtkbnFpMSBJ0A1MR02VFfuVH0eva4x6DEQLiSO0NvobxHYxe3As4fIV3S5R84eF+um0UE=
  - secure: wlrpltpDOLliO0sL6JUjZObiGVl3y+4Jk8v9cg68sXUWTwDXDO6n2YWhcv/gxPv/h9ls0ISqG3koWu+ORIXe+30o4oqFaVmpbFoY8xnl6nzZ/R5RuY6DLi4htePGEPpswAtbpLcy7xDtQweWJY/3MAzBWmhTFrr61pvtQ2b/+1fwsOi3lwRc8KoIfX5tvtF8gmPCve9mEMSL3jOcbvgimUs/CbD9MO3+z+9kB1V9Jnwq9gOynwBfD+F2L5Al9WZzjzQTm0iQi8hyJLmh/P6wEO8pBe2vvs6HduB5fnqhRho45/vBUKxy8bkNzpnAXAVMRSI/liorcaJQQQN9BOGQlfnz9SZv9K5DPqRZBi2OBY/AFTsh8L/A7QsPqMncZmglfTlLIiEU8cfm+zIv2tA4h28OSGWlH5MGhhP6Kj7a7GO9lzUEeMqUvy8PBmuI4NPP2Bx04zm6L0yoNQXk62egurqHqooIuNqrxtAxjMXi8/2IoPrTPtutKb7Yvv907PG127o7DhRvTT7T4ihr8qfJUC9sQn2nOyOE0ykC3KvS0Chd7DU3CwGRkIP/Rro+pJE2+7pM3Gvhr0WU3Sp63ldLh2kzDrGh7YIrhDz6e/zq5W1f5UXZ8ZRpfGUOjoAREmQWzUztqDzDP6W3PFy2IQbty6PiPlZuIZU2Pm9dtYEwO30=
  # GOOGLE
  - secure: oujoY36T8DSnJkpLH1KD2b0i8dt6E0Z7cDzm3WwrA/WEudOUFp4iSRfpZEGAzHCiFHwTckcFVVd9Ki/LwnsbEzonIjwWJ4DcKEUI86Xx/Q87tBXEHCbLA16TR+FpPBr2rCMbLsq2gzdD1QIdd4mjdvWIZ0xUE1pHei/aayF8BuCqB0+Sr1DV6gTSlmugqNoJYxD0aPhxqn7ODYnyPPBy9NX5ozZ/yTPQkMke42SG5juP+f6jpSsAL3qAPTH8aJX3XwuVoCrHA8MTY7tgeodmR4rAdpkPuNolfxBtJUP3i6O8T6bjNB5r0VVkMZ/ggrnhks76qXfb4dozHqIKapHDBr6q+c3MeW+hyhH3xtqdAOysm6N5RIkiRlrp7pbuVIk8DdW0DZ0Dt93TQxjZMsJa++8B2mUAHwrEJKUER37P94KTs/UbaJOuUc9JxwM5P1gUiJAD/AbAsCqqn0nshd0a2Ap5pp2WbFXBjzRF1kOnHd3zPv3wr3VVc53fzO+Vuo/xsoqoZB7sGffeERXah/YF9fKMoy4RErF+IYtRuQV5sbPO8mylddJq5jUs35+qaKVDGYZjx2Puh5ztL5Of5cSNmyzTn9qW7fThovoXlFw9t4ZVWma5SeQOrgP/J5eGBuDoTX5hEmkV2S2wuU5mwKlF/McfWEuasakiypsd2Mk3UYo=
  - secure: 1QJI1lGocxDteVnKuJIz8DOfbitKWObuZFghO2O1dweklZOhNmFQGo7bPEXRUYUtRH0z8wxnuda6jj/6NE3CifgOc//AZ3/vCC5fqHvTTYNC7L6Gn+UjlU8ICkZNlSq49Fn7ZIgdaCrfeQ95RnnTjDnSM2k2KnZw0ET/NKy0OIuEAAm01QIcj7QGbmCxoiDRQg5+mDKCd0vG44xJ5ckFkXK2PLVrPKuYcbwjahRFZyL80C4Qo0mWafVtMbM3Xid01znq9r+64Q+Hs204KEsjJJxGCusmMaZ4UeBNDTNg5nlyPsTX0M2plH1mOugC0HLvkj3n3h14rjj4M0dVg1LzXQGuy7Tsx5oXie2mlx71ksum9GPXU8nf4pBet7V8HF2knDVKlK1iM5HLlY3xd/O9P+WewY3J76xIB3w3TydAmbpOqUwVDmqbsj/KdAXo1jTPwDdZCfYLtCnhg6ldoKZ7k0Tkg8Grcl1ItTBkV3ov6Vr2PGBYqIaPDTMmkR+uNVIA8gWuIMqu+8Nh9XFKUoeolBfO4lJxii6vBhhw3s/1Cnvz/YPgbAiEGf3jFWeLaRTlRZpq8J1mk7NH2Nbt/610vFOROKFeW1l6YGSycR0uMqbz884u+MwR4/lcLRmFMDAajVzv2sgU1on1hM3AeGuphQesr5AgjevdVCQTRVZSJSU=
