language: python
python:
- '2.7'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
before_install:
- export DJANGO_SETTINGS_MODULE=mysite.settings
install:
- pip install -r requirements.txt
- pip install coveralls
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py test service.tests
- coverage run --source=service manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: h+B6fvBPx2YhH+bKwYWwp3IAqgdDiXdysLuHsjHMrBwIvDxfSPY7yCi0JywMbXBzUTf9X0zOY8M5IXsQ3C+46E3vYDHviwck+QnMrxNX+pLWbEgun3r3oyjvLygoUB23L8doWoIFIttfHyywmSB5E33j0GRxmIeUB3XqFFc515P4ZD+djjbuoNx8jSsLPrcyf5mzowSd6wWVbXHIaD349d6AYQmo7VmZKK0YxUqCgnnDHb9CR+gk4QxGFsZnbQR0wX4gzDtkEXT+Ng2crKyzjwassC6WAD3u8NMys7Rg42/lzk5D4mnUThsXDRDEdLPJ3idB4pKieVeH/U/yPBdJ8dZbx6fQ8/DMWTKPM+nT7dqH+jQmStLxfDM0XrPikDZswaQhyuofqul6xI5b2ronkdMzPaoBXN/tyUEXnfHUUjEfWu/o+CpoGOQoLmmv3/5/ElqufwoAjvp5zivMaVyTrxFG3MY1XHfETOr2M/91WDF3gahoOq3AJX9WKrbBAc6PoTy8q9Rc3ap38QtfD8pAvxAr5/Jp0SHfcVZ05o5HK/17xk4gbZa5wHZDiJSxcCG/NPzpNzSubw1pfnGOP7SUHr2JLf1Ln14mfWRut3cf2rsYRgPbhw1fWgEHSXjwc7z/6LUwbKlxtRMRZfZU2pMesr0Eeys6D1qKKWkSK/3TAug=
  app: zee-service-dev
  on:
    repo: zalokhan/Django-ServiceWebApp
env:
  global:
    secure: RPVrZwxWi6JkBSXlSF1Z3RUrKs5IW/Y6ADSee06Q4olLkQbbGMjnZYmx/NPCtq0LBRPHUJI+RF6gU6WuUr6zb+pbyVdOtpyGk82irbweB+9En02ekPYDmw3Au+3AKkvZW2sXD9Ap/HJlBSAzfGu4HIf3ZnsL0m3/jwozdt6dB1rT83BqpQZArWYcRvDNKJoLm1VvHheibGrOYSVMdmqcBzlRRQ+qptLrm2+ldH0+5vo6PGdfFJRU8FcgHQcFJf+cjt0JDZ3FnZXOZy+dwLHmu3nCENd/fhrZ6XGZ3XNzIgQ/R8c/5eG3UvveURGg2YPYg0pv7ZhjzUbjT8OSm22M2Gic3byat8ylE6vn13qD/rRdSWw9CsVqISUjf/oUbb48ZG68JjkOJTrsfKOm5bkYTs6fckNts2F4+EFYvJwUtkz0FZgiUEbiicxYUDeLpAjf0/SjLTl+ZVPeE803jv5tJ3DdidxIxa203cnSQsD2fWHXN0I43p6zOj+lXs2XyHvvXdlJfeSbs5f/CRP6rygwTrrib67We1QQweu3j6Xkd3st5Ap60AiqHiJRxj6Vn3Yc943O63wSUSNefr5V+j52d1zSyuzbiBSAJlFl7JE7WzwOr2CKEZh8dG1D3cFXil6J/t0QgDPwiNuTXF6/ZqNeI8aERnXPYd2j25RjcJqAQxA=
