language: python

python:
- '2.7'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
install: pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database MasterServiceDB;' -U postgres

script: python manage.py test service.tests

deploy:
  provider: heroku
  api_key:
    secure: h+B6fvBPx2YhH+bKwYWwp3IAqgdDiXdysLuHsjHMrBwIvDxfSPY7yCi0JywMbXBzUTf9X0zOY8M5IXsQ3C+46E3vYDHviwck+QnMrxNX+pLWbEgun3r3oyjvLygoUB23L8doWoIFIttfHyywmSB5E33j0GRxmIeUB3XqFFc515P4ZD+djjbuoNx8jSsLPrcyf5mzowSd6wWVbXHIaD349d6AYQmo7VmZKK0YxUqCgnnDHb9CR+gk4QxGFsZnbQR0wX4gzDtkEXT+Ng2crKyzjwassC6WAD3u8NMys7Rg42/lzk5D4mnUThsXDRDEdLPJ3idB4pKieVeH/U/yPBdJ8dZbx6fQ8/DMWTKPM+nT7dqH+jQmStLxfDM0XrPikDZswaQhyuofqul6xI5b2ronkdMzPaoBXN/tyUEXnfHUUjEfWu/o+CpoGOQoLmmv3/5/ElqufwoAjvp5zivMaVyTrxFG3MY1XHfETOr2M/91WDF3gahoOq3AJX9WKrbBAc6PoTy8q9Rc3ap38QtfD8pAvxAr5/Jp0SHfcVZ05o5HK/17xk4gbZa5wHZDiJSxcCG/NPzpNzSubw1pfnGOP7SUHr2JLf1Ln14mfWRut3cf2rsYRgPbhw1fWgEHSXjwc7z/6LUwbKlxtRMRZfZU2pMesr0Eeys6D1qKKWkSK/3TAug=
  app: zee-service-dev
  on:
    repo: zalokhan/Django-ServiceWebApp

