language: python
python:
- '2.7'
- '3.4'
- '3.5'
- 3.5-dev
- nightly

before_install:
- export DJANGO_SETTINGS_MODULE=mysite.settings

# Keep changing periodically
env:
  global:
    # SECRET_KEY
    - secure: OcEEIs/AWiImtzHFwBcykvc/RjOsrCDnXgtAmMgURhlvxhlaeWSTiaWmNfAJN57DdMVcsH5/36EPaDO3G3BEP+3En1CevkmqQU2rZXR1+wb+//Wiw/b69A5tMY7LD9CxT2wQqHI1+FnbZKqfAtiWVey70DjC0rPN+EaU32ozcDQG2hvgb4EF3gXg1pCRY72vcuA5mxRqWXjDBBkA9EVQ8NiQZguQLt22mb70p09epajxFOT1ZfWV7EFPct97AbFKADu2njmWLejQkR53zMVNX+jaKiMfBv1dWx7/JQeuAa5WUM31yCi9dOrwjzksRehBz5wTPOG/6pIELEpgkA58JI6h/bzAKqY2oXTJ9aN/vfbAT1mKdqURNcQUham3pLXlYVpwvWQ/aCQIKxa+s1RW+Ro90bl8yY6kqE3Qvtw+sxXQ72rBELpjaL/xAyXkI7w/dvPbTwyZDOtLvdD85N6z23fF6dPlvzNtRlWD/fTN7P7hgiltZa096r8J8go+/RMGrgMc3stx2kNen8yKpYy6Bxdd4Kn/OY1PwKjDljXF/gU9FYK8IOM8J2pjlhRDbHGMeFhBqG8lkyc3hgeCUbG4Jq45ZU9hgM1LRCI0tgI5PhkCp9p1EHFE1pwot/bpS9zWmV/v2TEzoKMD21O/yxcTaxrFumQHKQKpVvpiflLauy0=
    # SOCIAL
    # FB
    - secure: i2kNAnvJ5RLaAONVNDbS0iPLFjlz1PMydsXRNEVMgrWTXa9sa+EByuQYgEz9aQm2qBAdR859O8G2PaicSuucefRdsRRQ8z10MBM7wjL65DFsiy3GNZDucd1t+3BUrm213yCD+2Kqp37T0Id/iJIQUJtQh3PH9uM7WLN6nmJQ0TsMtZ0aybceWie9VSv/QuGE9QBl6l+DoVDGcgLYaSs/mcR04lJaWQ/Cg74fxpv+/dQvanSt6ozuZIkZUt9Zudy0GdNlAQbC0+6lOUeMe0i0oFnOnqBEGZAtYidoyxlnA7yY+m/jI6bI7ONwum3Hek7MINsEl8CO3sFpy2Xl4NE7koUDK76CHrsRrkauciXw/spMFB6fimyNwoUU2vN/aMPgtRn5r7arKPgdCbQfR3SaoLhbZvHI0TbCiEiORkOX77UtMKlnzwt0mOPknGT0YjTszzIeDueF8kK6UjUex3hlkCDTVMauPgxXa91yijFFnaOJ+PmzYbw0qTSeFYD2LovN3q73wLybs5sQNBBAlpXemZg5MS9E0pEx3Avv6CdbRYPv6hkDahP+7OAiT8aWcVziNwuwXvGHe3lbDV0gnO3A+UCyBqqiK5NU/QRmUz+oHB59FnSd5fgrpbAGpnTPyJm6V9wp26G0Sp6JG/1iUKajwYvKzT7Aw7y47Cf4IUhZyN4=
    - secure: OCxMkpXTJR99WiXpYRhPzt8iXqvuUxlVkCwZ59JgAyA6UFMVq6WuIRlsyz5o9AQi//S5wo5aFEWw285F/z8xMPj4IddmbQNYw2hSixXF/pev39Gv1JneGUhW3phNQUIpot4fpSF9GTgu0/xAnBTwALJbRMZSRKa+bkghY2y1+RSqgiT1aL63vtzNeuoT6UnPRY7FZpXpFqaM+0hf/4hqhA1aFl3c+HsZy0GvtGCu1qEzxZi8njIKjTdqqh9I94qkM7EdCchY+nVPqoYQq+L/AIndGrfcmQGdLs7zO8hcpMW24UZK7Ir+WhdkY2VJvyTjAjBSxng39wT9Pk/MChC9JcdE4ONp2Yp0ry0iUKYy8HWgozNq13Z3aPsygcGbEtlEROUzEG9sC4fCHSA1PS+0LrqvZUxpfsiw37D8AT8+hm6KuOxMUhuUP3qQVpivXiHiBZJzhN/w9wjmUT/bt32KE3IC/Uo8bJpUmznmNJhajaWz8DiRVEjZKDPqHCjMKI3nERv3cvcpgSQHoo6OMIIPiEcdHdZEIngmTN3nI7dnkOVjAQimLxhzVDfBO4Jyg5O04IVcN6be4hIBUP2Xrh5xy6xL1BKiJA25T3aiQbTblQutdIBCz36vD++bt/yiCz7OcKExapST5NGw5fCigiOzjkxvWohWX3RwShENLHKs16U=
    # GOOGLE
    - secure: WUtLU9pUtdAbBieX9+JIqIXQFgIWvD8h9GGh7v3xYN0YQcjyW2qHEmxDJjQB+/XlPk4gAukxWom836+7DTSRFQhC7xjiagI/3PJL/soTQwjJOyIfuN1CPSuNuVP/KiqlcKjJfGyonSlw/COGrdlG+j0tSqka0en6p9sBlriNTspxDAyQGeJypX0jvVAhvQFk/SVWbmGnPl2eCmNmJJy6HY9aV1iAmrcnAHMwa3cbrHPzySVmRNXGhcAQGSKf4l0R2aMRJ9dWy+DhNdIU0H3bEREIoh/B6YsgDnz8L4DhMjP9whOJ6QvIvcewk60d5GHRseriIUMtebBjk37PwvfiOx8gXGWbwgB7lBx34Dy1zl3PvJp2JqXiATjoJJF1lUr64H9OgjUz6gdqVQKS+J+2Q07Hj0eJY+/TJI4qRWomOmvPM3jJrj4THCtqnqwJPr6IohXyaFDhS2WsVK+fEpwRgBK1rvwQe1uOGCEwHoqEVsyQfaQ9aJt3fVVT6GL5T2CSGimIJsgqui5EFyrU+GWSfLAY2o1hg3uheOv8BrdB+MIvYcD1bBJftZw3KNti2HdnqEj0YMn5vQfex5bXEUlxM3Q9iL8nedlqrpOUNbXZ21qbqfGxgfxL3AiD19lagv87+TWfsP5c+/7NczkD/K7Cro2szCRhxBzWz22Z8kYzbV4=
    - secure: CFMQaRQr5RtqO9zcQQ3J7SCZvyKJQVbbYfTalTp2BYBVq7SrIpMeRqW7zAI4iDEBDbAWAqD8BEkAjk8udula1gvQ28X8dUIFbhgY4sQWcsrmxue4hIcWB+TxyTHbGIUjHn86ht+taCwuaiy0kFOA5AbSdyYKlMOtmcarg7GTg6UFK1BiH0iHgtyzrOxdbF3Ewmb/vGNw869qXuMzq+wq9fwQ+JNWRMUneiSYcJ9Davl7OyEvk3p1FcfVI3FlF8k+NHXWRQNbhBh3xHQJEGEm3vuGlR32sgvmpp+FTRv5tf6ft2va7mNJuFnki8eJvOslydh3Xy9dDlr2fhmpxKfH+1bk9kYo/P4woQhKFSBoklyEgnV60UBDsk258Wk3Oi/d2xn/sjDiMT297hUUwDDcXd/X2VhRLDXTvqS20CcD3rwML5UmxkMb96wvu4SAdL6rNcs0GEFw9M2DRldY8+hKzq4JOyaADzm/Pfu58iX4qC+QVdyEsNGZXUxI9fOpydmavifzh2vVzNVXgzbuX0snDEtXgr9tn+ol/YruzEYhyFTlOK4fXvODV4QM/jIy2ShBYtodIvrIXceF7cpHFRioimbuCCnet2htjeJjf3HBG6/hWZhDQkVq5zSUeYxmyLelAOzCVmfYjAKshcADOypRGdM7VFM812fQERm4XPelnHU=

install:
- pip install -r requirements.txt
- pip install coveralls

services:
- postgresql

before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres

script:
- python manage.py test service.tests
- coverage run --source=service manage.py test

after_success:
- coveralls

deploy:
  provider: heroku
  api_key:
    secure: h+B6fvBPx2YhH+bKwYWwp3IAqgdDiXdysLuHsjHMrBwIvDxfSPY7yCi0JywMbXBzUTf9X0zOY8M5IXsQ3C+46E3vYDHviwck+QnMrxNX+pLWbEgun3r3oyjvLygoUB23L8doWoIFIttfHyywmSB5E33j0GRxmIeUB3XqFFc515P4ZD+djjbuoNx8jSsLPrcyf5mzowSd6wWVbXHIaD349d6AYQmo7VmZKK0YxUqCgnnDHb9CR+gk4QxGFsZnbQR0wX4gzDtkEXT+Ng2crKyzjwassC6WAD3u8NMys7Rg42/lzk5D4mnUThsXDRDEdLPJ3idB4pKieVeH/U/yPBdJ8dZbx6fQ8/DMWTKPM+nT7dqH+jQmStLxfDM0XrPikDZswaQhyuofqul6xI5b2ronkdMzPaoBXN/tyUEXnfHUUjEfWu/o+CpoGOQoLmmv3/5/ElqufwoAjvp5zivMaVyTrxFG3MY1XHfETOr2M/91WDF3gahoOq3AJX9WKrbBAc6PoTy8q9Rc3ap38QtfD8pAvxAr5/Jp0SHfcVZ05o5HK/17xk4gbZa5wHZDiJSxcCG/NPzpNzSubw1pfnGOP7SUHr2JLf1Ln14mfWRut3cf2rsYRgPbhw1fWgEHSXjwc7z/6LUwbKlxtRMRZfZU2pMesr0Eeys6D1qKKWkSK/3TAug=
  app: bookturks
  on:
    repo: zalokhan/BookTurks

notifications:
  slack:
    rooms:
      secure: FO55O+KWRCR/o7m4CqXp4YeGMiqFcfjSAYaaKPk1Xb7RUxpTf6BYX/IS3duStppcNwigYwM0Vp7HcSigzfExStVAZ68I3w5+j+uwTLd1iT5HgxBM+70PPG8jFSRRYvs7ruthfRSPzSdx4Op+OdnjRUkjUVTTQdCWe3EVPMctwrdA5HgJNM3cITmGNf4MCkNUuPBC9j+SeHZDqivnDmiGgYYLHYGh7w3AcJTYzdSVrsS/R4xsstm97uCYs5JbtFMiVySZH+N+m8kHJ6TmS/rlcEkmVRTnfID7yN2vWjH53xThQoW4w/H+5DtCodM2BJnP10CKZFaepZumDT01L5+R+O0S8P95yX8+IVWZSauOsc+rLSfTEgowlBt3ZbichBzzYfECcKDizsoE6YuNw0VFM4VdyPgfciaDdz6+gTzVUI5nFvYflfIqwxN0mL7BpLx4SY9EBGIemK6kQwvwh7ICDaswjem2bEW6PX2VMdKpDkOTe0WLefWyNItkHyjlYa39AxKiIG5+waS6vpI3hiRApXF4nXG7nPvExyO9F9jo1umpPwjJRt2PxRO7F3MG8by4IwX1hHIiEaXgR0z+g707p3iXZONHpn0FBlDC533zvhR9+hOl9vskmCLxTcfP6DHPRr5CQtjAZD6ECX45tP2fAA/GvyIWcM3ZQvNJ2B7hNlE=